-- 코드를 입력하세요
SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM REST_INFO 
WHERE (FOOD_TYPE, FAVORITES) in 
	(select FOOD_TYPE, MAX(FAVORITES) from REST_INFO GROUP BY FOOD_TYPE)
    ORDER BY FOOD_TYPE desc