-- 코드를 입력하세요
SELECT ri.REST_ID, ri.REST_NAME, ri.FOOD_TYPE, ri.FAVORITES, ri.ADDRESS, ROUND(AVG(rr.REVIEW_SCORE), 2) as SCORE
FROM REST_REVIEW as rr
JOIN REST_INFO as ri
ON rr.REST_ID = ri.REST_ID
WHERE ri.ADDRESS like '서울%' 
GROUP BY rr.REST_ID
ORDER BY ROUND(AVG(rr.REVIEW_SCORE), 2) desc, ri.FAVORITES desc;