SELECT *
FROM (
    SELECT FO.PRODUCT_ID, FP.PRODUCT_NAME, SUM(FO.AMOUNT) * FP.PRICE as TOTAL_SALES
    FROM FOOD_ORDER as FO
    JOIN FOOD_PRODUCT as FP
    ON FO.PRODUCT_ID = FP.PRODUCT_ID
    WHERE MONTH(FO.PRODUCE_DATE) = 5
    GROUP BY FO.PRODUCT_ID
) as FO
ORDER BY FO.TOTAL_SALES desc, FO.PRODUCT_ID
;
